#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    # Attempt to auto-reconnect Cloud Connect tunnel if it was previously enabled
    echo "Checking Cloud Connect auto-reconnect..."
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        php /var/www/html/artisan cloud-connect:auto-reconnect
    else
        gosu $WWWUSER php /var/www/html/artisan cloud-connect:auto-reconnect
    fi

    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
