.git
.github
.gitignore
.gitattributes
.idea
.vscode
node_modules
tests
*.log
*.md
*.yml
*.yaml
.env*
.editorconfig
.prettierrc
phpunit.xml
README.md
CHANGELOG.md
docker-compose*
Dockerfile*
publish-docker-image.sh

# Vendor cleanup
vendor/**/*Test.php
vendor/**/*Tests.php
vendor/**/*.md
vendor/**/*.txt
vendor/**/*.dist
vendor/**/test
vendor/**/tests
vendor/**/docs
vendor/**/.git
vendor/**/.github

storage